version: '2'
services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-cli
    volumes:
    - ./:/var/www
    links:
    - mysql
    ports:
    - 9000
    tty:
      true

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_USER=app"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_DATABASE=app"
    ports:
    - "33061:3306"